version: "3.7"

services:
  docker-app:
    container_name: inventario-ws
    restart: always
    image: mxavier27/inventario:0.0.1-SNAPSHOT
    hostname: inventario-ws.com.br
    ports:
      - "9032:9032"
    depends_on:
      - docker-postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://docker-postgres:5432/inventory
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  docker-postgres:
    image: postgres:10.4
    restart: always
    ports:
      - 5433:5433
    environment:
      - POSTGRES_DB=inventory
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
    